### ISSUE TITLE
Homepage - Responsive Checking : At 991px, too wide space on both sides of the header, which makes it incorrect compared to the responsive design.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Lost-Racing-Products#18]
![18](https://cloud.githubusercontent.com/assets/18256652/16571963/ddd1d4b6-4295-11e6-99d6-711cef589f2f.png)

**Comment by joancapuyan** [comment]
I think the left side image is for desktop view design and I believe that the desktop view starts at 992px :)
