### ISSUE TITLE
Product - Category & Listing : Should paginate after 12 items as per scope and design.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Lost-Racing-Products#26]
![26](https://cloud.githubusercontent.com/assets/18256652/16573377/b02262fa-42a5-11e6-89e8-fb03fe40a1ac.png)

**Comment by iteano** [comment]
From Product Listing
![26a](https://cloud.githubusercontent.com/assets/18256652/16574593/38c2e2b2-42b3-11e6-810b-6cd38aba07b0.png)

**Comment by joancapuyan** [comment]
Not possible to implement pagination in woocommerce categories page
