### ISSUE TITLE
Header - Cart : Didn't open checkout page after clicking the cart while it is empty, which makes it inconsistent from the old site.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Lost-Racing-Products#3]
![3](https://cloud.githubusercontent.com/assets/18256652/16551583/996b274a-41ec-11e6-87dd-5f3040c48f54.png)

**Comment by joancapuyan** [comment]
It is the default behavior of Woocommerce when you click on the empty cart it will link to cart page, you cannot go to checkout page if the cart is empty.

The old site is not using Woocommerce plugin.
